### ISSUE TITLE
Callback Error

### ISSUE THREAD

**Issue by msfconsoleUwU** [halfstackpgr/T-DevX-Project-Disposed-#1]
![Screenshot_20220504-184354_Termux](https://user-images.githubusercontent.com/75271686/166689547-8b9bea4c-eb13-4202-98f0-d11b0d4c7677.png)
There is a problem with this. Fix

**Comment by msfconsoleUwU** [comment]
There is a problem with editing that needs to fixed. Will do that ASAP. But still will take time.

**Comment by msfconsoleUwU** [comment]
Done.

**Comment by halfstackpgr** [comment]
wtf bitch ?
